### ISSUE TITLE
Messages are dropped

### ISSUE THREAD

**Issue by rohitjoshi** [op/go-nanomsg#18]
Hello,
  I am using mq-benchmarking (https://github.com/tylertreat/mq-benchmarking/blob/master/benchmark/mq/nanomsg.go) to test the latency for nanomsg.

e.g
./mq-benchmarking  nanomsg  true 50000 256

It is dropping the messages.  I did try to increase the  send and receive buffer size but it doesn't helps upto certain extent.

If you use my  modified version of mq-benchmarking project (https://github.com/rohitjoshi/mq-benchmarking)  which has more logging, you can see messages are dropped. 
<pre>
./bin/mq-benchmarking  nanomsg  true 50000 256
2014/11/02 19:48:42 mq-benchmarking subject=nanomsg test-latency=true  msg-count=50000  msg-size=256
2014/11/02 19:48:42 Begin nanomsg test
2014/11/02 19:48:42 Setup is invoked
2014/11/02 19:48:45 TestLatency:Sending 50000 message...
2014/11/02 19:48:45 Sent 50000 messages in 97.141968 ms
2014/11/02 19:48:45 Sent 514710.593750 per second
2014/11/02 19:48:45 Receiver started
2014/11/02 19:48:45 Mean latency for 50000 messages: 73.490311 ms
2014/11/02 19:48:45 Latency: Max=97.206200 ms,  Min=56.200539 ms,
2014/11/02 19:48:45 Number of messages above mean latency: 19895
2014/11/02 19:48:45 Number of messages below mean latency: 19517
2014/11/02 19:48:45 Number of messages with mean latency: 0
2014/11/02 19:48:45 End nanomsg test
</pre>

Here if you see, total messages received are 19895 + 19517 = 39412.  It should have received 50,000 messages.

Do you know how can this be solved?

**Comment by gdamore** [comment]
The problem is indeed almost certainly that you are sending faster than you are consuming.  This will cause messages to get dropped.  Under the hood nanomsg is very much a best effort, and once you push messages faster than the transport can accommodate, we just toss them on the floor -- particularly for multicast protocols like PUB/SUB.  (This is the only sane way to handle this, otherwise a slow consumer could actually perform a kind of denial-of-service against other subscribers by just subscribing and not consuming quickly.)

Buffering approaches (I guess this is what ZMQ uses) can be used to provide some mitigation for bursty situations, but they really aren't a fix.  If you want to PUB/SUB, you need to rate limit your PUB to something sane, and expect the occasional dropped message.  (sequence counters can be used in your payload to help with this.)

I recommend closing this as not a bug.  There is nothing to be done to fix this in the language binding.

**Comment by op** [comment]
@gdamore Thanks for taking your time to explain. Much appreciated. :)
